---
apiVersion: "gateway.networking.k8s.io/v1beta1"
kind: "HTTPRoute"
metadata:
  name: "01ee61ad-619d-14f8-a740-d4bd9c9332a2"
  labels:
    api-name: "a368f7729e9dc835c4c2aace246a69695dbca274"
    api-version: "91e95be6b6634e3c21072dfcd661146728694326"
    organization: "7505d64a54e061b7acd54ccd58b49dc43500b635"
    managed-by: "apk"
spec:
  hostnames:
  - "default.gw.wso2.com"
  rules:
  - matches:
    - path:
        type: "RegularExpression"
        value: "/greeting"
      method: "GET"
    filters: []
    backendRefs:
    - group: "dp.wso2.com"
      kind: "Backend"
      name: "backend-d881b288aa68f008ee98a6a2cc8bbbce144d8c22-api"
  parentRefs:
  - group: "gateway.networking.k8s.io"
    kind: "Gateway"
    name: "default"
    sectionName: "httpslistener"
