---
kind: "ConfigMap"
apiVersion: "v1"
metadata:
  name: "8a1e734c05334eb931e15e8f764d35740d07edb1-definition"
  labels:
    api-name: "a368f7729e9dc835c4c2aace246a69695dbca274"
    api-version: "91e95be6b6634e3c21072dfcd661146728694326"
    organization: "7505d64a54e061b7acd54ccd58b49dc43500b635"
    managed-by: "apk"
binaryData:
  definition: "H4sIAAAAAAAA/32SwU7DMAyGX2XKGa1l3HqDC5qQAAlxQjtErdtFtEnmOLBR9d2xXTaGkNZLmny/7d9ORhMieBudqczNslyuzNXCON8GU42GHPXA4M7W7+Cbxe3zWvAHYHLBM7jmiNJMfJYA5dhUb6PJ2DMrzLRRUGd0dFDSQGtzT/y/URgtbZNUKjoEIOc72XRAsqQ8DBY50NwfIYc0kGp0kWYD54QbQSvn64ZJd0aiRTsAHf153rBCF+2WN7sMXOpf/scfDcIuOwROTJhB2qKDjqYNOIgA9rEPDfzyeguD1SEeoggTobiZtG+EFINPoL2vylKWv4WfHiRrHTyB12kQ7KmIvRW344X0/F2c+szrMLABTq0OjuoXyTqbOsWcKgSbaavPo+3Dp4rcEHtXO1UJDei+9AZe9QVsiWKqioIg0ZIrGp0LX5MET/P3DdspfJiAAgAA"
