---
apiVersion: "dp.wso2.com/v1alpha1"
kind: "Backend"
metadata:
  name: "backend-d881b288aa68f008ee98a6a2cc8bbbce144d8c22-api"
  labels:
    api-name: "a368f7729e9dc835c4c2aace246a69695dbca274"
    api-version: "91e95be6b6634e3c21072dfcd661146728694326"
    organization: "7505d64a54e061b7acd54ccd58b49dc43500b635"
    managed-by: "apk"
spec:
  services:
  - host: "backendservice.backend-dev.svc.cluster.local"
    port: 9090
  basePath: ""
  protocol: "http"
